AspNet/Controllers/PageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AspNet.Models;

namespace AspNet.Controllers
{
    public class PageController : Controller
    {
       
        public ActionResult Index()
        {
            //return Redirect("/story/number/2");
           
            Story story = new Story();
            
            try
            {
                story.GenerateList("3");
                return View(story);
            }
            catch (SomeSqlException ex)
            {
                return new ErrorConrtoller().ErrorActionResult(ex);
            }
            catch (Exception ex)
            {
                return new ErrorConrtoller().ErrorActionResult(ex);
            }
        }

        public ActionResult About()
        {
            return View();

        }
    }
}

AspNet/Controllers/StoryController.cs
using AspNet.Models;
using System;
using System.Collections.Generic;
using System.Drawing.Design;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace AspNet.Controllers
{
    public class StoryController : Controller
    {

        private Story story;

        public StoryController()
        {
            story = new Story();
        }

        // GET: Story
        public ActionResult Index()
        {
            return Redirect("/page");
        }

        public ActionResult Random()
        {

            try
            {
                story.Random();
                return View("Number", story);
            }
            catch (SomeSqlException ex)
            {
                return new ErrorConrtoller().ErrorActionResult(ex);
            }
        }

        [HttpGet]
        public ActionResult Add()
        {
            story.Title ="";
            story.Text = "";
            story.Email ="";
            try
            {
                return View(story);
            }
            catch (SomeSqlException ex)
            {
                return new ErrorConrtoller().ErrorActionResult(ex);
            }
            
        }

        [HttpPost]
        public ActionResult Add(Story post)
        {
            if (!ModelState.IsValid) // 
                return View(post);

            story.Title = post.Title;
            story.Text  = post.Text;
            story.Email = post.Email;

            try
            {
                story.Add();
                return Redirect("/story/number/" + story.Id);
            }
            catch (SomeSqlException ex)
            {
                return new ErrorConrtoller().ErrorActionResult(ex);
            }
        }


        public ActionResult Number()
        {
            long id;
            if(!long.TryParse(RouteData.Values["id"].ToString(), out id))
                return Redirect("/page");

            try
            {
                story.Number(id);
                return View(story);
            }
            catch (SomeSqlException ex)
            {
                return new ErrorConrtoller().ErrorActionResult(ex);
            }
        }

        private void PreparationPageError(SomeSqlException ex)
        {
            ViewBag.Query = ex.Query;
            ViewBag.Exception = ex.GetType();
            ViewBag.Message = ex.Message;
            ViewBag.TargetSite = ex.TargetSite;
            string[] stackTraces;
            try
            {
                stackTraces = ex.StackTrace.Replace(@") в ", ") -> ").Replace(@" в ", "|").Split('|');
            }
            catch (NullReferenceException)
            {
                stackTraces = new[] { "" };
            }
            ViewBag.StackTraces = stackTraces;
            ViewBag.InnerException = ex.InnerException;
        }

    }
}

AspNet/Controllers/UserController.cs
using System;
using AspNet.Models;
using System.Web.Mvc;

namespace AspNet.Controllers
{
    public class UserController : Controller
    {
        private User user;

        public UserController()
        {
            user = new User();
        }

        [HttpGet]
        public ActionResult Index()
        {
            try
            {
                return View(user);
            }
            catch (SomeSqlException ex)
            {
                return new ErrorConrtoller().ErrorActionResult(ex);
            }
            
        }


        [HttpPost]
        public ActionResult Index(User userPost)
        {
            user.Login = userPost.Login;
            user.Password = userPost.Password;
            
            try
            {
                userPost.Checklogin();
                if (userPost.Status == "1")
                    Session["admin"] = "1";

                return View(userPost);

            }
            catch (SomeSqlException ex)
            {
                return new ErrorConrtoller().ErrorActionResult(ex);
            }
            catch (Exception ex)
            {
                return new ErrorConrtoller().ErrorActionResult(ex);
            }
        }


        public ActionResult Logout(string s)
        {
            try
            {

            user = new User();
            Session["admin"] = "";
            return View("Index", user);

            }
            catch (SomeSqlException ex)
            {
                return new ErrorConrtoller().ErrorActionResult(ex);
            }
            catch (Exception ex)
            {
                return new ErrorConrtoller().ErrorActionResult(ex);
            }
        }

        public ActionResult Checker()
        {
            if ((string) Session["admin"] != "1")
                return Redirect("Index");
            Story story = new Story();
            ViewBag.IsChecker = story.SelectWaitStory();

            return View(story);
        }

        public ActionResult Approve()
        {
            if ((string) Session["admin"] != "1")
                return Redirect("Index");
            string id = (RouteData.Values["id"] ?? "").ToString();
            Story story = new Story();
            story.Approve(id);
            return Redirect("~/User/Checker");
        }

        public ActionResult Decline()
        {
            if ((string) Session["admin"] != "1")
                return Redirect("Index");
            string id = (RouteData.Values["id"] ?? "").ToString();
            Story story = new Story();
            story.Decline(id);
            return Redirect("~/User/Checker");
        }
    }
}

AspNet/Views/Shared/_Design.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Story</title>
    <link rel="icon" type="Image/png" href="/Images/Story.png" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
@helper CurrentItem(string item)
{
    if (item == ViewContext.RouteData.Values["controller"].ToString() + "/" + 
                ViewContext.RouteData.Values["action"].ToString())
    {
        @:class="active"
    }
}
<body>
<div id="header" class="col-lg-12">
    <div class="col-lg-2"></div>
    <div class="col-lg-8">
        <ul class="nav nav-pills">
            <li @CurrentItem("Page/Index")>     @Html.ActionLink("Свежие",           "Index",    "Page",     new {area = ""}, new {@class = "navbar-brand"})</li>
            <li @CurrentItem("Story/Random")>   @Html.ActionLink("Случайная",        "Random",   "Story",    new {area = ""}, new {@class = "navbar-brand"})</li>
            <li @CurrentItem("Story/Add")>      @Html.ActionLink("Прислать историю", "Add",      "Story", new { area = "" }, new { @class = "navbar-brand" })</li>
            <li @CurrentItem("User/Index")>     @Html.ActionLink("Вход", "Index", "User", new { area = "" }, new { @class = "navbar-brand" })</li>
            @if (Session["admin"] == "1")
            {
                <li @CurrentItem("User/Checker")> @Html.ActionLink("Проверка", "Checker", "User", new { area = "" }, new { @class = "navbar-brand" })</li>
            }
        </ul>
    </div>
    <div class="col-lg-2"></div>
</div>

<div id="container" class="col-lg-12">
    <div class="col-lg-2"></div>
    <div class="col-lg-8">
        @RenderBody()
    </div>
    <div class="col-lg-2"></div>
</div>
     
<div id="footer" class="col-lg-12">
    <hr/>
    <div class="col-lg-2"></div>
    <div class="col-lg-8">
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <div class="col-lg-2"></div>
</div>

</body>
</html>

AspNet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Свежие",              "Index",    "Page",     new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Случайная",           "Random",   "Story",    new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Прислать историю",    "Add",      "Story",    new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("О проекте",           "Abuut",    "Page",     new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>